### ISSUE TITLE
Connection to the rotki backend was not possible

### ISSUE THREAD

**Issue by diega** [dappnode/DAppNodePackage-rotki#68]
Rotki doesn't start

1. Install version `0.1.34`
2. Go to http://rotki.dappnode
3. See error
```
Connection failure
A connection to the rotki backend was not possible, would you like to retry again? 
```

**DAppNode version:**

- Package version: 0.1.34 (v1.34.3 upstream)
- OS: Home i754
- Browser: Firefox

**Additional context**
These are the logs I see over an over
```
INFO:monitor:Preparing to cleanup tmp directory
INFO:monitor:Deleted 0 files or directories, skipped 0 from /tmp
INFO:monitor:no config file provided
INFO:monitor:loading config from env
INFO:monitor:starting rotki backend
INFO:monitor:starting nginx
42
2024/09/12 03:54:39 [notice] 10#10: using the "epoll" event method
2024/09/12 03:54:39 [notice] 10#10: nginx/1.25.5
2024/09/12 03:54:39 [notice] 10#10: built by gcc 12.2.0 (Debian 12.2.0-14) 
2024/09/12 03:54:39 [notice] 10#10: OS: Linux 5.10.0-32-amd64
2024/09/12 03:54:39 [notice] 10#10: getrlimit(RLIMIT_NOFILE): 1048576:1048576
2024/09/12 03:54:39 [notice] 10#10: start worker processes
2024/09/12 03:54:39 [notice] 10#10: start worker process 11
2024/09/12 03:54:39 [notice] 10#10: start worker process 12
2024/09/12 03:54:39 [notice] 10#10: start worker process 13
2024/09/12 03:54:39 [notice] 10#10: start worker process 14
2024/09/12 03:54:39 [notice] 10#10: start worker process 15
2024/09/12 03:54:39 [notice] 10#10: start worker process 16
2024/09/12 03:54:39 [notice] 10#10: start worker process 17
2024/09/12 03:54:39 [notice] 10#10: start worker process 18
2024/09/12 03:54:39 [notice] 10#10: start worker process 19
2024/09/12 03:54:39 [notice] 10#10: start worker process 20
2024/09/12 03:54:39 [notice] 10#10: start worker process 21
2024/09/12 03:54:39 [notice] 10#10: start worker process 22
eth_utils/network.py:44: UserWarning: Network 345 with name 'Yooldo Verse Mainnet' does not have a valid ChainId. eth-typing should be updated with the latest networks.
eth_utils/network.py:44: UserWarning: Network 12611 with name 'Astar zkEVM' does not have a valid ChainId. eth-typing should be updated with the latest networks.
Traceback (most recent call last):
  File "rotkehlchen-script.py", line 2, in <module>
  File "rotkehlchen/__main__.py", line 37, in main
  File "rotkehlchen/server.py", line 71, in main
  File "rotkehlchen/api/server.py", line 498, in start
  File "gevent/baseserver.py", line 336, in start
  File "gevent/pywsgi.py", line 1669, in init_socket
  File "gevent/pywsgi.py", line 1681, in update_environ
  File "gevent/_socketcommon.py", line 286, in getfqdn
  File "gevent/_socketcommon.py", line 252, in gethostbyaddr
  File "gevent/resolver/thread.py", line 66, in gethostbyaddr
  File "gevent/pool.py", line 161, in apply
  File "gevent/threadpool.py", line 546, in spawn
  File "gevent/threadpool.py", line 492, in adjust
  File "gevent/threadpool.py", line 472, in _adjust_step
  File "gevent/threadpool.py", line 499, in _add_thread
  File "gevent/threadpool.py", line 106, in __init__
RuntimeError: can't start new thread
[23] Failed to execute script 'rotkehlchen-script' due to unhandled exception!
rotki REST API server is running at: 0.0.0.0:4242 with loglevel TRACE
2024/09/12 03:55:09 [error] 11#11: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: _, request: "GET /api/1/ping HTTP/1.1", upstream: "http://127.0.0.1:4242/api/1/ping", host: "localhost"
2024/09/12 03:55:09 [warn] 11#11: *1 upstream server temporarily disabled while connecting to upstream, client: 127.0.0.1, server: _, request: "GET /api/1/ping HTTP/1.1", upstream: "http://127.0.0.1:4242/api/1/ping", host: "localhost"
2024/09/12 03:55:09 [error] 11#11: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 127.0.0.1, server: _, request: "GET /api/1/ping HTTP/1.1", upstream: "http://127.0.0.1:4242/api/1/ping", host: "localhost"
2024/09/12 03:55:09 [warn] 11#11: *1 upstream server temporarily disabled while connecting to upstream, client: 127.0.0.1, server: _, request: "GET /api/1/ping HTTP/1.1", upstream: "http://127.0.0.1:4242/api/1/ping", host: "localhost"
127.0.0.1 - - [12/Sep/2024:03:55:09 +0000] "GET /api/1/ping HTTP/1.1" 502 497 "-" "curl/7.88.1" "-"
ERROR:monitor:rotki has terminated exiting
```

**Comment by timjrobinson** [comment]
I also can't access it at http://rotki.dappnode. My normal dappnode is running at http://dappnode.local or http://my.dappnode (both work). How is this subdomain supposed to propagate over the network?
